FIND_PROGRAM(
	QUICKBOOK_COMMAND quickbook
)
MARK_AS_ADVANCED(QUICKBOOK_COMMAND)

FIND_PROGRAM(
	QUICKBOOK_COMMAND_VERSIONED quickbook-${QUICKBOOK_VERSION}
)
MARK_AS_ADVANCED(QUICKBOOK_COMMAND_VERSIONED)

IF(QUICKBOOK_COMMAND)
	SET(REAL_QUICKBOOK_COMMAND ${QUICKBOOK_COMMAND})
ENDIF ()

IF(QUICKBOOK_COMMAND_VERSIONED)
	SET(REAL_QUICKBOOK_COMMAND ${QUICKBOOK_COMMAND_VERSIONED})
ENDIF ()

MARK_AS_ADVANCED(REAL_QUICKBOOK_COMMAND)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	QUICKBOOK
	DEFAULT_MSG
	REAL_QUICKBOOK_COMMAND
)

IF(QUICKBOOK_FOUND)
	SET(QUICKBOOK_EXECUTABLE ${REAL_QUICKBOOK_COMMAND})
ELSE()
	SET(QUICKBOOK_EXECUTABLE)
ENDIF()
