FIND_PATH(FCPPT_INCLUDE_DIR NAMES fcppt/config.h)
MARK_AS_ADVANCED(FCPPT_INCLUDE_DIR)

FIND_LIBRARY(FCPPT_LIBRARY NAMES fcppt)
MARK_AS_ADVANCED(FCPPT_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FCPPT DEFAULT_MSG FCPPT_LIBRARY FCPPT_INCLUDE_DIR)

IF(FCPPT_FOUND)
  SET(FCPPT_LIBRARIES ${FCPPT_LIBRARY})
  SET(FCPPT_INCLUDE_DIRS ${FCPPT_INCLUDE_DIR})
ELSE(FCPPT_FOUND)
  SET(FCPPT_LIBRARIES)
  SET(FCPPT_INCLUDE_DIRS)
ENDIF(FCPPT_FOUND)
