pkg_check_modules(FCPPT fcppt)

IF(NOT FCPPT_FOUND)
	FIND_PATH(FCPPT_INCLUDE_DIR NAMES fcppt/config.h)
	MARK_AS_ADVANCED(FCPPT_INCLUDE_DIR)

	FIND_LIBRARY(FCPPT_LIBRARY NAMES fcppt)
	MARK_AS_ADVANCED(FCPPT_LIBRARY)

	SET(FCPPT_LIBRARIES ${FCPPT_LIBRARY})
	SET(FCPPT_INCLUDE_DIRS ${FCPPT_INCLUDE_DIR})
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FCPPT DEFAULT_MSG FCPPT_LIBRARIES FCPPT_INCLUDE_DIRS)
