#ifndef FCPPT_MATH_VECTOR_VECTOR_HPP_INCLUDED
#define FCPPT_MATH_VECTOR_VECTOR_HPP_INCLUDED

#include <fcppt\math\vector\angle_between.hpp>
#include <fcppt\math\vector\angle_between_cast.hpp>
#include <fcppt\math\vector\arithmetic.hpp>
#include <fcppt\math\vector\atan2.hpp>
#include <fcppt\math\vector\basic.hpp>
#include <fcppt\math\vector\basic_decl.hpp>
#include <fcppt\math\vector\basic_fwd.hpp>
#include <fcppt\math\vector\basic_impl.hpp>
#include <fcppt\math\vector\before.hpp>
#include <fcppt\math\vector\comparison.hpp>
#include <fcppt\math\vector\construct.hpp>
#include <fcppt\math\vector\cross.hpp>
#include <fcppt\math\vector\dim.hpp>
#include <fcppt\math\vector\dot.hpp>
#include <fcppt\math\vector\dynamic.hpp>
#include <fcppt\math\vector\dynamic_impl.hpp>
#include <fcppt\math\vector\has_dim.hpp>
#include <fcppt\math\vector\hypersphere_to_cartesian.hpp>
#include <fcppt\math\vector\input.hpp>
#include <fcppt\math\vector\is_null.hpp>
#include <fcppt\math\vector\length.hpp>
#include <fcppt\math\vector\length_square.hpp>
#include <fcppt\math\vector\make.hpp>
#include <fcppt\math\vector\max_ctor_params.hpp>
#include <fcppt\math\vector\mod.hpp>
#include <fcppt\math\vector\narrow_cast.hpp>
#include <fcppt\math\vector\normal_storage.hpp>
#include <fcppt\math\vector\normalize.hpp>
#include <fcppt\math\vector\orthogonalize.hpp>
#include <fcppt\math\vector\output.hpp>
#include <fcppt\math\vector\place.hpp>
#include <fcppt\math\vector\project.hpp>
#include <fcppt\math\vector\signed_angle.hpp>
#include <fcppt\math\vector\signed_angle_cast.hpp>
#include <fcppt\math\vector\slerp.hpp>
#include <fcppt\math\vector\static.hpp>
#include <fcppt\math\vector\structure_cast.hpp>
#include <fcppt\math\vector\to_angle.hpp>
#include <fcppt\math\vector\transform.hpp>
#include <fcppt\math\vector\unit.hpp>
#include <fcppt\math\vector\unit_circle.hpp>

#endif
