#ifndef FCPPT_MATH_MATH_HPP_INCLUDED
#define FCPPT_MATH_MATH_HPP_INCLUDED

#include <fcppt\math\almost_zero.hpp>
#include <fcppt\math\box\box.hpp>
#include <fcppt\math\ceil_div.hpp>
#include <fcppt\math\clamp.hpp>
#include <fcppt\math\compare.hpp>
#include <fcppt\math\deg_to_rad.hpp>
#include <fcppt\math\diff.hpp>
#include <fcppt\math\difference_type.hpp>
#include <fcppt\math\dim\dim.hpp>
#include <fcppt\math\exception.hpp>
#include <fcppt\math\generate_binary_vectors.hpp>
#include <fcppt\math\instantiate_arithmetic.hpp>
#include <fcppt\math\interpolation\interpolation.hpp>
#include <fcppt\math\inverse.hpp>
#include <fcppt\math\is_dynamic_size.hpp>
#include <fcppt\math\is_negative.hpp>
#include <fcppt\math\is_power_of_2.hpp>
#include <fcppt\math\is_rational.hpp>
#include <fcppt\math\is_static_size.hpp>
#include <fcppt\math\log.hpp>
#include <fcppt\math\machine_epsilon.hpp>
#include <fcppt\math\matrix\matrix.hpp>
#include <fcppt\math\mod.hpp>
#include <fcppt\math\mod_assign.hpp>
#include <fcppt\math\nearly_equals.hpp>
#include <fcppt\math\next_pow_2.hpp>
#include <fcppt\math\null.hpp>
#include <fcppt\math\pi.hpp>
#include <fcppt\math\point_rotate.hpp>
#include <fcppt\math\quad.hpp>
#include <fcppt\math\quaternion\quaternion.hpp>
#include <fcppt\math\rad_to_deg.hpp>
#include <fcppt\math\range_compare.hpp>
#include <fcppt\math\round_div_int.hpp>
#include <fcppt\math\signum.hpp>
#include <fcppt\math\size_type.hpp>
#include <fcppt\math\sphere\sphere.hpp>
#include <fcppt\math\twopi.hpp>
#include <fcppt\math\vector\vector.hpp>

#endif
