#ifndef FCPPT_RATIO_RATIO_HPP_INCLUDED
#define FCPPT_RATIO_RATIO_HPP_INCLUDED

#include <fcppt\ratio\add.hpp>
#include <fcppt\ratio\add_fwd.hpp>
#include <fcppt\ratio\atto.hpp>
#include <fcppt\ratio\centi.hpp>
#include <fcppt\ratio\deca.hpp>
#include <fcppt\ratio\deci.hpp>
#include <fcppt\ratio\divide.hpp>
#include <fcppt\ratio\divide_fwd.hpp>
#include <fcppt\ratio\equal.hpp>
#include <fcppt\ratio\equal_fwd.hpp>
#include <fcppt\ratio\exa.hpp>
#include <fcppt\ratio\femto.hpp>
#include <fcppt\ratio\giga.hpp>
#include <fcppt\ratio\greater.hpp>
#include <fcppt\ratio\greater_equal.hpp>
#include <fcppt\ratio\greater_equal_fwd.hpp>
#include <fcppt\ratio\greater_fwd.hpp>
#include <fcppt\ratio\hecto.hpp>
#include <fcppt\ratio\int_type.hpp>
#include <fcppt\ratio\is_object.hpp>
#include <fcppt\ratio\kilo.hpp>
#include <fcppt\ratio\less.hpp>
#include <fcppt\ratio\less_equal.hpp>
#include <fcppt\ratio\less_equal_fwd.hpp>
#include <fcppt\ratio\less_fwd.hpp>
#include <fcppt\ratio\mega.hpp>
#include <fcppt\ratio\micro.hpp>
#include <fcppt\ratio\milli.hpp>
#include <fcppt\ratio\multiply.hpp>
#include <fcppt\ratio\multiply_fwd.hpp>
#include <fcppt\ratio\nano.hpp>
#include <fcppt\ratio\not_equal.hpp>
#include <fcppt\ratio\not_equal_fwd.hpp>
#include <fcppt\ratio\object.hpp>
#include <fcppt\ratio\object_fwd.hpp>
#include <fcppt\ratio\peta.hpp>
#include <fcppt\ratio\pico.hpp>
#include <fcppt\ratio\substract.hpp>
#include <fcppt\ratio\substract_fwd.hpp>
#include <fcppt\ratio\tera.hpp>

#endif
