#ifndef FCPPT_CONFIG_H_INCLUDED
#define FCPPT_CONFIG_H_INCLUDED

/* #undef FCPPT_HAVE_VARIADIC_TEMPLATES */
#define FCPPT_HAVE_ATLEAST_UINT64
/* #undef FCPPT_HAVE_DEFAULTED_AND_DELETED_FUNCTIONS */
#define FCPPT_NARROW_STRING
#define FCPPT_HAVE_CLOCK_GETTIME
#define FCPPT_STRING_IS_UTF8
#define FCPPT_HAS_GNU_DEMANGLE
#define FCPPT_HAVE_GCC_PRAGMA_MESSAGE

#ifdef _WIN32
#define FCPPT_WINDOWS_PLATFORM 1
#elif defined(FCPPT_HAVE_POSIX)
#define FCPPT_POSIX_PLATFORM 1
#ifdef __APPLE__
#define FCPPT_DARWIN_PLATFORM
#endif
#endif

#ifdef __GNUC__
#define FCPPT_HAVE_GCC_VISIBILITY
#endif

#endif
