include(
	GNUInstallDirs
)

set(
	FCPPT_UTILS_PROJECT_SOURCE_DIR
	"${${PROJECT_NAME}_SOURCE_DIR}"
)

set(
	FCPPT_UTILS_PROJECT_BINARY_DIR
	"${${PROJECT_NAME}_BINARY_DIR}"
)

set(
	FCPPT_UTILS_INSTALL_DATA_DIR
	"${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}"
)

set(
	FCPPT_UTILS_INSTALL_CMAKEMODULES_DIR
	"${FCPPT_UTILS_INSTALL_DATA_DIR}/cmake"
)

set(
	FCPPT_UTILS_INSTALL_CMAKECONFIG_DIR_BASE
	"${CMAKE_INSTALL_LIBDIR}/cmake"
)

set(
	FCPPT_UTILS_INSTALL_CMAKECONFIG_DIR
	"${FCPPT_UTILS_INSTALL_CMAKECONFIG_DIR_BASE}/${PROJECT_NAME}"
)

foreach(
	curdir
	DATA_DIR
	CMAKEMODULES_DIR
	CMAKECONFIG_DIR_BASE
	CMAKECONFIG_DIR
)
	GNUInstallDirs_get_absolute_install_dir(
		FCPPT_UTILS_INSTALL_FULL_${curdir}
		FCPPT_UTILS_INSTALL_${curdir}
		${curdir}
	)
endforeach()

# configure standard CMake build paths
set(
	CMAKE_RUNTIME_OUTPUT_DIRECTORY
	${FCPPT_UTILS_PROJECT_BINARY_DIR}/bin
)

set(
	CMAKE_LIBRARY_OUTPUT_DIRECTORY
	${FCPPT_UTILS_PROJECT_BINARY_DIR}/lib
)

set(
	CMAKE_ARCHIVE_OUTPUT_DIRECTORY
	${FCPPT_UTILS_PROJECT_BINARY_DIR}/lib
)
