name: CMake

on:
  push:
    branches:
    - "master"
    - "cicd"
  pull_request:
    branches:
    - "master"
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  buildMac:
    name: Build macOS
    env:
      FLAGS: -Wno-poison-system-directories
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install libs
      run: brew install boost catch2

    - name: Configure CMake
      run: CFLAGS=${{env.FLAGS}} CXXFLAGS=${{env.FLAGS}} cmake -B ${{github.workspace}}/build
        -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -D ENABLE_TEST=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  buildWin:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '782ccc18d8b819cdef6794a6c03eb3d9f7cd04aa'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
        -D "CMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake"
        -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -D "VCPKG_INSTALLED_DIR=${{runner.temp}}/vcpkg_installed"
        -D ENABLE_BOOST=ON
        -D ENABLE_CATCH=ON
        -D ENABLE_TEST=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

