name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  buildMac:
    name: Build macOS
    env:
      FLAGS: -Wno-poison-system-directories
    runs-on: macOS-latest

    steps:
    - name: Install tools
      run: brew install boost catch2

    - uses: actions/checkout@v4

    - name: Configure CMake
      run: CFLAGS=${{env.FLAGS}} CXXFLAGS=${{env.FLAGS}} cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_TEST=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  buildWin:
    name: Build Windows
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D ENABLE_BOOST=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

